name: Continuous Integration and Continuous Deployment

on:
  push:
    branches:
        - milestone5

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.Deployment }}'

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bloodwise-ai

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Deployment Container 
        run: |-
          cd ${{ github.workspace }}/src/deployment/
          docker build -t bloodwise-app-deployment -f Dockerfile .

      - name: Create credentials directory and file
        run: |
            mkdir -p ${{ github.workspace }}/credentials
            echo '${{ secrets.Deployment }}' > ${{ github.workspace }}/credentials/deployment.json

      - name: Run Deploy App
        run: |-
          docker run --rm --name bloodwise-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/vector-db:/vector-db \
            --volume $GITHUB_WORKSPACE:/workspace \
            -v ${{ github.workspace }}/credentials:/credentials \
            -e Deployment=/credentials/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=bloodwise-ai \
            -e GCP_ZONE=us-central1-a \
            bloodwise-app-deployment bash deploy-k8s-update.sh